Refactor/cra
e-cordel/ecordel-frontend pull request #11
Opened 2021-10-29 03:20 UTC by samuelclerod

# Pull Request Title

short description

what was changed?

 - refactor basic cordel list from nextjs-10 to creat-react-app structure
 - must to implement cordel details

2021-10-31 09:46 UTC, itsmemarioss requested changes
Alguns arquivos apagados por esse commit devem continuar no repositório.
License, notice, actions...

Além disso, poderia resolver os 5 code smells apontados pelo sonar?

2021-10-31 09:46 UTC, itsmemarioss commented on .github/pull_request_template.md
> -# Pull Request Title
Por que apagar esse arquivo?

2021-10-31 09:46 UTC, itsmemarioss commented on .github/workflows/main.yml
> -name: deploy-to-ftp
Por que apagar esse arquivo?

2021-10-31 09:46 UTC, itsmemarioss commented on LICENSE
> -                                 Apache License
Reverter essa exclusão.

2021-10-31 09:46 UTC, itsmemarioss commented on .github/workflows/merge.yml
> -name: merge-develop-into-master
Por que apagar esse arquivo?

2021-10-31 09:46 UTC, itsmemarioss commented on NOTICE
> -e-cordel REST API
Reverter essa exclusão.

2021-10-31 12:04 UTC, samuelclerod commented on NOTICE
> -e-cordel REST API
Na troca da estrutura acabei removendo os arquivos 😅. Vamos rejeitar o PR pra resolver esses code smells, incluir revisão de cordeis, paginação e colocar na pipeline o serviço pra dev. Talvez valha a pena colocar um branch de develop e deixar a main só pra produção.

2021-11-01 11:21 UTC, closed without merging

2021-11-01 11:22 UTC, samuelclerod commented
Using extental repos not able to use secret keys. Flow this thread on PR #13