fix: cordel-viewer
e-cordel/ecordel-frontend pull request #17
Opened 2021-11-04 22:03 UTC by samuelclerod

# Pull Request Title

short description

what was changed?
- fix: ecordel viewer component

2021-11-06 15:58 UTC, itsmemarioss requested changes
o que acha de adicionarmos testes para esses comportamentos?
- toParagraphs
- toLines
- getSourceLink

2021-11-06 16:39 UTC, samuelclerod commented
> o que acha de adicionarmos testes para esses comportamentos?
> 
> * toParagraphs
> * toLines
> * getSourceLink

Acho que vale a pena sim!

2021-11-07 11:57 UTC, itsmemarioss commented on .github/workflows/ci_review.yml
> +        run: yarn test
Dessa forma os testes não são executados com watcher com interactive CLI? O runner das actions faz set da `CI`?

2021-11-07 12:00 UTC, itsmemarioss commented on .github/workflows/ci_review.yml
> +        run: yarn test
mystery solved
https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

2021-11-07 12:00 UTC, itsmemarioss approved these changes

2021-11-07 12:02 UTC, merged