Create CordelGridViewer component. Create AuthorDetails page
e-cordel/ecordel-frontend pull request #39
Opened 2023-05-06 18:18 UTC by JDanielT

# Pull Request Title

Create CordelGridViewer component and AuthorDetails page

what was changed?

 - Created CordelGridViewer
 - Created AuthorDetails page
 - Added route /autores/:id
 - Changed Home to use CordelGridViewer component

2023-05-07 09:10 UTC, itsmemarioss reviewed
Esse PR só pode ser merged depois do PR 49 do backend
https://github.com/e-cordel/ecordel-restapi/pull/49

2023-05-07 09:10 UTC, itsmemarioss commented on src/routes/index.tsx
> +        <Route path="/autores/:id" exact component={AuthorDetails} isPrivate />
Essa rota não deveria ser pública como a rota `/cordeis/:id` 
```suggestion
        <Route path="/autores/:id" exact component={AuthorDetails} />

```

2023-05-09 21:56 UTC, itsmemarioss requested changes

2023-05-09 21:56 UTC, itsmemarioss commented on src/pages/authors/AuthorDetails.tsx
> +    const {data: cordels} = useFetch<any, Error>(`cordels/summaries?author_id=${id}`);
o nome do parâmetro está errado, deveria ser `authorId`

2023-05-10 01:15 UTC, JDanielT commented on src/pages/authors/AuthorDetails.tsx
> +    const {data: cordels} = useFetch<any, Error>(`cordels/summaries?author_id=${id}`);
done

2023-05-10 08:36 UTC, itsmemarioss approved these changes

2023-05-10 08:41 UTC, merged